export const testData = {
    cod: "200",
    message: 0,
    cnt: 40,
    list: [
        {
            dt: 1658502000,
            main: {
                temp: 20.04,
                feels_like: 19.8,
                temp_min: 18.6,
                temp_max: 20.04,
                pressure: 1020,
                sea_level: 1020,
                grnd_level: 1019,
                humidity: 65,
                temp_kf: 1.44,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            clouds: {
                all: 40,
            },
            wind: {
                speed: 4.45,
                deg: 72,
                gust: 6.01,
            },
            visibility: 10000,
            pop: 0.74,
            rain: {
                "3h": 1.27,
            },
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-22 15:00:00",
        },
        {
            dt: 1658512800,
            main: {
                temp: 19.57,
                feels_like: 19.25,
                temp_min: 18.62,
                temp_max: 19.57,
                pressure: 1020,
                sea_level: 1020,
                grnd_level: 1018,
                humidity: 64,
                temp_kf: 0.95,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 58,
            },
            wind: {
                speed: 3.53,
                deg: 82,
                gust: 4.45,
            },
            visibility: 10000,
            pop: 0.68,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-22 18:00:00",
        },
        {
            dt: 1658523600,
            main: {
                temp: 18.25,
                feels_like: 17.91,
                temp_min: 17.36,
                temp_max: 18.25,
                pressure: 1019,
                sea_level: 1019,
                grnd_level: 1019,
                humidity: 68,
                temp_kf: 0.89,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 80,
            },
            wind: {
                speed: 2.81,
                deg: 75,
                gust: 4.32,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2022-07-22 21:00:00",
        },
        {
            dt: 1658534400,
            main: {
                temp: 16.11,
                feels_like: 15.76,
                temp_min: 16.11,
                temp_max: 16.11,
                pressure: 1019,
                sea_level: 1019,
                grnd_level: 1019,
                humidity: 76,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 86,
            },
            wind: {
                speed: 1.98,
                deg: 88,
                gust: 4.5,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2022-07-23 00:00:00",
        },
        {
            dt: 1658545200,
            main: {
                temp: 15.48,
                feels_like: 15.2,
                temp_min: 15.48,
                temp_max: 15.48,
                pressure: 1019,
                sea_level: 1019,
                grnd_level: 1019,
                humidity: 81,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 90,
            },
            wind: {
                speed: 0.97,
                deg: 123,
                gust: 1.42,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2022-07-23 03:00:00",
        },
        {
            dt: 1658556000,
            main: {
                temp: 16.9,
                feels_like: 16.55,
                temp_min: 16.9,
                temp_max: 16.9,
                pressure: 1019,
                sea_level: 1019,
                grnd_level: 1019,
                humidity: 73,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 83,
            },
            wind: {
                speed: 1.54,
                deg: 182,
                gust: 2.43,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-23 06:00:00",
        },
        {
            dt: 1658566800,
            main: {
                temp: 21.56,
                feels_like: 21.18,
                temp_min: 21.56,
                temp_max: 21.56,
                pressure: 1019,
                sea_level: 1019,
                grnd_level: 1019,
                humidity: 54,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 87,
            },
            wind: {
                speed: 2.72,
                deg: 229,
                gust: 3.71,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-23 09:00:00",
        },
        {
            dt: 1658577600,
            main: {
                temp: 25.59,
                feels_like: 25.04,
                temp_min: 25.59,
                temp_max: 25.59,
                pressure: 1018,
                sea_level: 1018,
                grnd_level: 1018,
                humidity: 32,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 93,
            },
            wind: {
                speed: 3.44,
                deg: 257,
                gust: 4.35,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-23 12:00:00",
        },
        {
            dt: 1658588400,
            main: {
                temp: 27.99,
                feels_like: 26.96,
                temp_min: 27.99,
                temp_max: 27.99,
                pressure: 1017,
                sea_level: 1017,
                grnd_level: 1017,
                humidity: 27,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 71,
            },
            wind: {
                speed: 2.7,
                deg: 243,
                gust: 4.39,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-23 15:00:00",
        },
        {
            dt: 1658599200,
            main: {
                temp: 25.43,
                feels_like: 25.07,
                temp_min: 25.43,
                temp_max: 25.43,
                pressure: 1017,
                sea_level: 1017,
                grnd_level: 1017,
                humidity: 40,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 81,
            },
            wind: {
                speed: 5.65,
                deg: 221,
                gust: 6.16,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-23 18:00:00",
        },
        {
            dt: 1658610000,
            main: {
                temp: 20.89,
                feels_like: 20.6,
                temp_min: 20.89,
                temp_max: 20.89,
                pressure: 1018,
                sea_level: 1018,
                grnd_level: 1018,
                humidity: 60,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 98,
            },
            wind: {
                speed: 3.54,
                deg: 221,
                gust: 7.4,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2022-07-23 21:00:00",
        },
        {
            dt: 1658620800,
            main: {
                temp: 18.63,
                feels_like: 18.4,
                temp_min: 18.63,
                temp_max: 18.63,
                pressure: 1018,
                sea_level: 1018,
                grnd_level: 1017,
                humidity: 71,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 88,
            },
            wind: {
                speed: 3.51,
                deg: 217,
                gust: 8.81,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2022-07-24 00:00:00",
        },
        {
            dt: 1658631600,
            main: {
                temp: 18.57,
                feels_like: 18.44,
                temp_min: 18.57,
                temp_max: 18.57,
                pressure: 1017,
                sea_level: 1017,
                grnd_level: 1016,
                humidity: 75,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.68,
                deg: 208,
                gust: 9.87,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2022-07-24 03:00:00",
        },
        {
            dt: 1658642400,
            main: {
                temp: 19.42,
                feels_like: 19.27,
                temp_min: 19.42,
                temp_max: 19.42,
                pressure: 1016,
                sea_level: 1016,
                grnd_level: 1016,
                humidity: 71,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 89,
            },
            wind: {
                speed: 4.81,
                deg: 212,
                gust: 11.37,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-24 06:00:00",
        },
        {
            dt: 1658653200,
            main: {
                temp: 24.71,
                feels_like: 24.44,
                temp_min: 24.71,
                temp_max: 24.71,
                pressure: 1016,
                sea_level: 1016,
                grnd_level: 1015,
                humidity: 46,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01d",
                },
            ],
            clouds: {
                all: 3,
            },
            wind: {
                speed: 5.93,
                deg: 221,
                gust: 9.12,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-24 09:00:00",
        },
        {
            dt: 1658664000,
            main: {
                temp: 28.53,
                feels_like: 27.85,
                temp_min: 28.53,
                temp_max: 28.53,
                pressure: 1014,
                sea_level: 1014,
                grnd_level: 1014,
                humidity: 36,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: "Clouds",
                    description: "few clouds",
                    icon: "02d",
                },
            ],
            clouds: {
                all: 17,
            },
            wind: {
                speed: 6.53,
                deg: 219,
                gust: 9.56,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-24 12:00:00",
        },
        {
            dt: 1658674800,
            main: {
                temp: 29.52,
                feels_like: 28.53,
                temp_min: 29.52,
                temp_max: 29.52,
                pressure: 1012,
                sea_level: 1012,
                grnd_level: 1012,
                humidity: 33,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01d",
                },
            ],
            clouds: {
                all: 10,
            },
            wind: {
                speed: 6.66,
                deg: 217,
                gust: 9.8,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-24 15:00:00",
        },
        {
            dt: 1658685600,
            main: {
                temp: 27.3,
                feels_like: 26.83,
                temp_min: 27.3,
                temp_max: 27.3,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 1011,
                humidity: 35,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: "Clouds",
                    description: "few clouds",
                    icon: "02d",
                },
            ],
            clouds: {
                all: 13,
            },
            wind: {
                speed: 6.03,
                deg: 228,
                gust: 10.6,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-24 18:00:00",
        },
        {
            dt: 1658696400,
            main: {
                temp: 23.3,
                feels_like: 22.89,
                temp_min: 23.3,
                temp_max: 23.3,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 1010,
                humidity: 46,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 83,
            },
            wind: {
                speed: 3.79,
                deg: 223,
                gust: 9.47,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2022-07-24 21:00:00",
        },
        {
            dt: 1658707200,
            main: {
                temp: 20.24,
                feels_like: 20.23,
                temp_min: 20.24,
                temp_max: 20.24,
                pressure: 1010,
                sea_level: 1010,
                grnd_level: 1010,
                humidity: 73,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 86,
            },
            wind: {
                speed: 3.98,
                deg: 226,
                gust: 10.07,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2022-07-25 00:00:00",
        },
        {
            dt: 1658718000,
            main: {
                temp: 19.32,
                feels_like: 19.27,
                temp_min: 19.32,
                temp_max: 19.32,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 1009,
                humidity: 75,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.87,
                deg: 227,
                gust: 9.31,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2022-07-25 03:00:00",
        },
        {
            dt: 1658728800,
            main: {
                temp: 18.82,
                feels_like: 18.66,
                temp_min: 18.82,
                temp_max: 18.82,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 1009,
                humidity: 73,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 4.79,
                deg: 239,
                gust: 9.76,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-25 06:00:00",
        },
        {
            dt: 1658739600,
            main: {
                temp: 21.87,
                feels_like: 21.42,
                temp_min: 21.87,
                temp_max: 21.87,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 1009,
                humidity: 50,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 5.96,
                deg: 250,
                gust: 9.1,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-25 09:00:00",
        },
        {
            dt: 1658750400,
            main: {
                temp: 25.49,
                feels_like: 25.03,
                temp_min: 25.49,
                temp_max: 25.49,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 1008,
                humidity: 36,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 74,
            },
            wind: {
                speed: 7,
                deg: 264,
                gust: 10.41,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-25 12:00:00",
        },
        {
            dt: 1658761200,
            main: {
                temp: 23.83,
                feels_like: 23.44,
                temp_min: 23.83,
                temp_max: 23.83,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 1009,
                humidity: 45,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 79,
            },
            wind: {
                speed: 6.1,
                deg: 255,
                gust: 9.7,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-25 15:00:00",
        },
        {
            dt: 1658772000,
            main: {
                temp: 23.36,
                feels_like: 22.85,
                temp_min: 23.36,
                temp_max: 23.36,
                pressure: 1009,
                sea_level: 1009,
                grnd_level: 1009,
                humidity: 42,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 80,
            },
            wind: {
                speed: 5.42,
                deg: 254,
                gust: 8.34,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-25 18:00:00",
        },
        {
            dt: 1658782800,
            main: {
                temp: 21.32,
                feels_like: 20.87,
                temp_min: 21.32,
                temp_max: 21.32,
                pressure: 1011,
                sea_level: 1011,
                grnd_level: 1011,
                humidity: 52,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 99,
            },
            wind: {
                speed: 4.33,
                deg: 270,
                gust: 7.35,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2022-07-25 21:00:00",
        },
        {
            dt: 1658793600,
            main: {
                temp: 18.76,
                feels_like: 18.44,
                temp_min: 18.76,
                temp_max: 18.76,
                pressure: 1012,
                sea_level: 1012,
                grnd_level: 1012,
                humidity: 67,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 99,
            },
            wind: {
                speed: 4.18,
                deg: 274,
                gust: 8.35,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2022-07-26 00:00:00",
        },
        {
            dt: 1658804400,
            main: {
                temp: 16.6,
                feels_like: 16.22,
                temp_min: 16.6,
                temp_max: 16.6,
                pressure: 1013,
                sea_level: 1013,
                grnd_level: 1012,
                humidity: 73,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: "Clouds",
                    description: "few clouds",
                    icon: "02n",
                },
            ],
            clouds: {
                all: 17,
            },
            wind: {
                speed: 3.45,
                deg: 285,
                gust: 6.8,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "n",
            },
            dt_txt: "2022-07-26 03:00:00",
        },
        {
            dt: 1658815200,
            main: {
                temp: 16.4,
                feels_like: 16.03,
                temp_min: 16.4,
                temp_max: 16.4,
                pressure: 1014,
                sea_level: 1014,
                grnd_level: 1014,
                humidity: 74,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 801,
                    main: "Clouds",
                    description: "few clouds",
                    icon: "02d",
                },
            ],
            clouds: {
                all: 12,
            },
            wind: {
                speed: 3.57,
                deg: 311,
                gust: 6.06,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-26 06:00:00",
        },
        {
            dt: 1658826000,
            main: {
                temp: 20.1,
                feels_like: 19.45,
                temp_min: 20.1,
                temp_max: 20.1,
                pressure: 1015,
                sea_level: 1015,
                grnd_level: 1015,
                humidity: 49,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 53,
            },
            wind: {
                speed: 4.03,
                deg: 311,
                gust: 5.13,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-26 09:00:00",
        },
        {
            dt: 1658836800,
            main: {
                temp: 23.66,
                feels_like: 23.1,
                temp_min: 23.66,
                temp_max: 23.66,
                pressure: 1015,
                sea_level: 1015,
                grnd_level: 1015,
                humidity: 39,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 64,
            },
            wind: {
                speed: 2.94,
                deg: 325,
                gust: 3.59,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-26 12:00:00",
        },
        {
            dt: 1658847600,
            main: {
                temp: 22.33,
                feels_like: 21.77,
                temp_min: 22.33,
                temp_max: 22.33,
                pressure: 1015,
                sea_level: 1015,
                grnd_level: 1015,
                humidity: 44,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.34,
                deg: 33,
                gust: 2.56,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-26 15:00:00",
        },
        {
            dt: 1658858400,
            main: {
                temp: 19.72,
                feels_like: 19.39,
                temp_min: 19.72,
                temp_max: 19.72,
                pressure: 1016,
                sea_level: 1016,
                grnd_level: 1015,
                humidity: 63,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 4.27,
                deg: 91,
                gust: 5.02,
            },
            visibility: 10000,
            pop: 0,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-26 18:00:00",
        },
        {
            dt: 1658869200,
            main: {
                temp: 17.58,
                feels_like: 17.43,
                temp_min: 17.58,
                temp_max: 17.58,
                pressure: 1017,
                sea_level: 1017,
                grnd_level: 1016,
                humidity: 78,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10n",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.9,
                deg: 87,
                gust: 6.6,
            },
            visibility: 10000,
            pop: 0.24,
            rain: {
                "3h": 0.25,
            },
            sys: {
                pod: "n",
            },
            dt_txt: "2022-07-26 21:00:00",
        },
        {
            dt: 1658880000,
            main: {
                temp: 17.38,
                feels_like: 17.16,
                temp_min: 17.38,
                temp_max: 17.38,
                pressure: 1017,
                sea_level: 1017,
                grnd_level: 1016,
                humidity: 76,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04n",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.43,
                deg: 90,
                gust: 5.89,
            },
            visibility: 10000,
            pop: 0.02,
            sys: {
                pod: "n",
            },
            dt_txt: "2022-07-27 00:00:00",
        },
        {
            dt: 1658890800,
            main: {
                temp: 17.02,
                feels_like: 16.79,
                temp_min: 17.02,
                temp_max: 17.02,
                pressure: 1016,
                sea_level: 1016,
                grnd_level: 1016,
                humidity: 77,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10n",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.13,
                deg: 99,
                gust: 6.32,
            },
            visibility: 10000,
            pop: 0.26,
            rain: {
                "3h": 0.13,
            },
            sys: {
                pod: "n",
            },
            dt_txt: "2022-07-27 03:00:00",
        },
        {
            dt: 1658901600,
            main: {
                temp: 16.6,
                feels_like: 16.38,
                temp_min: 16.6,
                temp_max: 16.6,
                pressure: 1017,
                sea_level: 1017,
                grnd_level: 1016,
                humidity: 79,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.1,
                deg: 114,
                gust: 6.67,
            },
            visibility: 10000,
            pop: 0.54,
            rain: {
                "3h": 0.57,
            },
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-27 06:00:00",
        },
        {
            dt: 1658912400,
            main: {
                temp: 18.55,
                feels_like: 18.16,
                temp_min: 18.55,
                temp_max: 18.55,
                pressure: 1017,
                sea_level: 1017,
                grnd_level: 1017,
                humidity: 65,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            clouds: {
                all: 100,
            },
            wind: {
                speed: 3.72,
                deg: 118,
                gust: 5.31,
            },
            visibility: 10000,
            pop: 0.52,
            rain: {
                "3h": 0.29,
            },
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-27 09:00:00",
        },
        {
            dt: 1658923200,
            main: {
                temp: 21.59,
                feels_like: 21.08,
                temp_min: 21.59,
                temp_max: 21.59,
                pressure: 1017,
                sea_level: 1017,
                grnd_level: 1017,
                humidity: 49,
                temp_kf: 0,
            },
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            clouds: {
                all: 97,
            },
            wind: {
                speed: 3.69,
                deg: 116,
                gust: 3.84,
            },
            visibility: 10000,
            pop: 0.44,
            sys: {
                pod: "d",
            },
            dt_txt: "2022-07-27 12:00:00",
        },
    ],
    city: {
        id: 7302135,
        name: "Abbey Wood",
        coord: {
            lat: 51.5,
            lon: 0.12,
        },
        country: "GB",
        population: 13000,
        timezone: 3600,
        sunrise: 1658462913,
        sunset: 1658520181,
    },
}
